version: 2
jobs:
  # The build job
  build:
    docker:
      - image: circleci/node
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
          working_directory: ~/project/client
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: yarn install
          working_directory: ~/project/client
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
          working_directory: ~/project/client
      # Build project with different configuration based on
      # the current branch
      - run:
          name: Building
          command: npm run build
          working_directory: ~/project/client
      # Cache the dist folder for the deploy job
      - add_ssh_keys:
          fingerprints:
            - "14:6c:5d:10:58:c0:a2:9e:6a:b4:9d:31:02:3e:82:00"
      - run: echo $FINGERPRINT >> ~/.ssh/known_hosts
      - deploy:
          command: scp -r dist/sync-me/* root@$SERVER:/var/www/sync-me.video
          working_directory: ~/project/client
